services:
  - type: web
    name: codebattle
    runtime: node
    plan: free
    buildCommand: npm run install:all && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_VERSION
        value: "22.5.0"
      - key: ADMIN_PASSWORD
        sync: false
