const express=require('express');const http=require('http');const {Server}=require('socket.io');const {DatabaseSync}=require('node:sqlite');const bcrypt=require('bcryptjs');const crypto=require('crypto');const {spawn}=require('child_process');const path=require('path');const fs=require('fs');
const app=express();const server=http.createServer(app);const allowedOrigin=process.env.CLIENT_ORIGIN||true;const io=new Server(server,{cors:{origin:allowedOrigin,credentials:true}});app.use(express.json({limit:'1mb'}));app.use(require('cookie-parser')());
const dbPath=process.env.DB_PATH||path.join(__dirname,'../data/codebattle.db');fs.mkdirSync(path.dirname(dbPath),{recursive:true});const db=new DatabaseSync(dbPath);db.exec('PRAGMA journal_mode=WAL');try{db.exec('ALTER TABLE Users ADD COLUMN is_admin INTEGER DEFAULT 0')}catch{}db.exec(`CREATE TABLE IF NOT EXISTS Users(id TEXT PRIMARY KEY,username TEXT UNIQUE NOT NULL,password_hash TEXT,created_at INTEGER NOT NULL,is_admin INTEGER DEFAULT 0);CREATE TABLE IF NOT EXISTS GuestSessions(id TEXT PRIMARY KEY,guest_id TEXT,last_active INTEGER,expires_at INTEGER);CREATE TABLE IF NOT EXISTS Matches(id TEXT PRIMARY KEY,player1 TEXT,player2 TEXT,language TEXT,difficulty TEXT,status TEXT,winner TEXT,ranked INTEGER,created_at INTEGER);CREATE TABLE IF NOT EXISTS Rounds(id TEXT PRIMARY KEY,match_id TEXT,round_number INTEGER,saboteur TEXT,debugger TEXT,challenge_id TEXT,result TEXT);CREATE TABLE IF NOT EXISTS Leaderboard(user_id TEXT,difficulty TEXT,points INTEGER DEFAULT 0,wins INTEGER DEFAULT 0,PRIMARY KEY(user_id,difficulty));CREATE TABLE IF NOT EXISTS Sessions(token TEXT PRIMARY KEY,user_id TEXT,expires_at INTEGER);CREATE TABLE IF NOT EXISTS Feedback(id TEXT PRIMARY KEY,user_id TEXT,username TEXT,type TEXT NOT NULL,subject TEXT NOT NULL,description TEXT NOT NULL,game_id TEXT,status TEXT DEFAULT 'open',created_at INTEGER NOT NULL);`);
const challenges=[
{id:'js-beg-arr',title:'Repair the Total',difficulty:'beginner',category:'Arrays',language:'javascript',problem:'Given an array of integers, return the sum of all numbers in the array. The function must work for empty arrays.',input:'An array of integers.',output:'A single integer containing the sum.',constraints:'0 ≤ n ≤ 1000; -10^4 ≤ a[i] ≤ 10^4.',exampleInput:'[2, 4, 6]',exampleOutput:'12',referenceSolution:`function solve(arr) {\n  let total = 0;\n  for (let i = 0; i < arr.length; i++) {\n    total += arr[i];\n  }\n  return total;\n}`,tests:[{name:'basic',input:'[2,4,6]',output:'12'},{name:'negative',input:'[-5,2,3]',output:'0'},{name:'empty',input:'[]',output:'0'}],hidden:[{name:'hidden-mix',input:'[100,-50,25,-75,10]',output:'10'},{name:'hidden-single',input:'[999]',output:'999'}]},
{id:'js-beg-str',title:'Find the First Vowel',difficulty:'beginner',category:'Strings',language:'javascript',problem:'Return the index of the first vowel (a, e, i, o, u) in a lowercase string. Return -1 if there is no vowel.',input:'A lowercase string.',output:'The zero-based index of the first vowel, or -1.',constraints:'0 ≤ length ≤ 500.',exampleInput:'"debug"',exampleOutput:'1',referenceSolution:`function solve(s) {\n  for (let i = 0; i < s.length; i++) {\n    if ('aeiou'.includes(s[i])) return i;\n  }\n  return -1;\n}`,tests:[{name:'debug',input:'"debug"',output:'1'},{name:'rhythm',input:'"rhythm"',output:'-1'},{name:'apple',input:'"apple"',output:'0'}],hidden:[{name:'late-vowel',input:'"bcdfgou"',output:'5'},{name:'empty',input:'""',output:'-1'}]},
{id:'js-int-loop',title:'Count Even Values',difficulty:'intermediate',category:'Loops',language:'javascript',problem:'Count how many values in an integer array are even. Negative values and zero must be handled correctly.',input:'An array of integers.',output:'The number of even integers.',constraints:'0 ≤ n ≤ 5000.',exampleInput:'[1,2,3,4,6]',exampleOutput:'3',referenceSolution:`function solve(arr) {\n  let count = 0;\n  for (const value of arr) {\n    if (value % 2 === 0) count++;\n  }\n  return count;\n}`,tests:[{name:'mixed',input:'[1,2,3,4,6]',output:'3'},{name:'negative',input:'[-2,-3,0,5]',output:'2'}],hidden:[{name:'all-even',input:'[-8,-4,0,2,10]',output:'5'},{name:'all-odd',input:'[-5,-3,1,7]',output:'0'}]},
{id:'js-int-search',title:'Binary Search Index',difficulty:'intermediate',category:'Searching',language:'javascript',problem:'Given a sorted array and a target, return the target index using binary search. Return -1 when it is absent.',input:'A JSON object {arr, target}.',output:'The target index or -1.',constraints:'arr is sorted ascending; 0 ≤ n ≤ 10000.',exampleInput:'{"arr":[1,3,5,7],"target":5}',exampleOutput:'2',referenceSolution:`function solve(data) {\n  let lo = 0, hi = data.arr.length - 1;\n  while (lo <= hi) {\n    const mid = Math.floor((lo + hi) / 2);\n    if (data.arr[mid] === data.target) return mid;\n    if (data.arr[mid] < data.target) lo = mid + 1;\n    else hi = mid - 1;\n  }\n  return -1;\n}`,tests:[{name:'found',input:'{"arr":[1,3,5,7],"target":5}',output:'2'},{name:'absent',input:'{"arr":[2,4,6,8],"target":5}',output:'-1'}],hidden:[{name:'edge-left',input:'{"arr":[-10,-5,0,5,10],"target":-10}',output:'0'},{name:'edge-right',input:'{"arr":[1,2,3,4,5],"target":5}',output:'4'}]},
{id:'js-adv-math',title:'Longest Increasing Run',difficulty:'advanced',category:'Algorithms',language:'javascript',problem:'Return the length of the longest contiguous strictly increasing run in an integer array. A single element has length 1; an empty array has length 0.',input:'An array of integers.',output:'An integer length.',constraints:'0 ≤ n ≤ 100000.',exampleInput:'[1,2,2,3,4,1,5]',exampleOutput:'2',referenceSolution:`function solve(arr) {\n  if (arr.length === 0) return 0;\n  let best = 1, run = 1;\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] > arr[i - 1]) run++;\n    else run = 1;\n    if (run > best) best = run;\n  }\n  return best;\n}`,tests:[{name:'plateau',input:'[1,2,2,3,4,1,5]',output:'2'},{name:'increasing',input:'[1,2,3,4]',output:'4'}],hidden:[{name:'empty',input:'[]',output:'0'},{name:'long-run',input:'[-3,-2,-1,0,2,5,4,6]',output:'6'}]},
];
const pyEquivalent={
 'js-beg-arr':`def solve(arr):\n    total = 0\n    for value in arr:\n        total += value\n    return total`,
 'js-beg-str':`def solve(s):\n    for i, ch in enumerate(s):\n        if ch in 'aeiou':\n            return i\n    return -1`,
 'js-int-loop':`def solve(arr):\n    return sum(1 for value in arr if value % 2 == 0)`,
 'js-int-search':`def solve(data):\n    lo, hi = 0, len(data['arr']) - 1\n    while lo <= hi:\n        mid = (lo + hi) // 2\n        if data['arr'][mid] == data['target']: return mid\n        if data['arr'][mid] < data['target']: lo = mid + 1\n        else: hi = mid - 1\n    return -1`,
 'js-adv-math':`def solve(arr):\n    if not arr: return 0\n    best = run = 1\n    for i in range(1, len(arr)):\n        if arr[i] > arr[i-1]: run += 1\n        else: run = 1\n        best = max(best, run)\n    return best`
};

// Procedural challenge library. Every challenge is generated from a fresh seed, so
// the app is not limited to a short list of fixed questions.
const proceduralTemplates = [
 {id:'arr-max',difficulty:'beginner',category:'Arrays',title:'Find the Peak',statement:'Return the largest integer in the array. Return 0 for an empty array.',input:'An array of integers.',output:'The largest integer, or 0 when the array is empty.',constraints:'0 ≤ n ≤ 1000; -10^4 ≤ a[i] ≤ 10^4.',make(){const a=Array.from({length:randInt(0,12)},()=>randInt(-100,100));return {input:a,output:a.length?Math.max(...a):0}},js:`function solve(arr) {\n  if (arr.length === 0) return 0;\n  let best = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] > best) best = arr[i];\n  }\n  return best;\n}`,py:`def solve(arr):\n    if not arr: return 0\n    best = arr[0]\n    for i in range(1, len(arr)):\n        if arr[i] > best: best = arr[i]\n    return best`},
 {id:'arr-min',difficulty:'beginner',category:'Arrays',title:'Find the Low Point',statement:'Return the smallest integer in the array. Return 0 for an empty array.',input:'An array of integers.',output:'The smallest integer, or 0 when the array is empty.',constraints:'0 ≤ n ≤ 1000; -10^4 ≤ a[i] ≤ 10^4.',make(){const a=Array.from({length:randInt(0,12)},()=>randInt(-100,100));return {input:a,output:a.length?Math.min(...a):0}},js:`function solve(arr) {\n  if (arr.length === 0) return 0;\n  let best = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] < best) best = arr[i];\n  }\n  return best;\n}`,py:`def solve(arr):\n    if not arr: return 0\n    best = arr[0]\n    for i in range(1, len(arr)):\n        if arr[i] < best: best = arr[i]\n    return best`},
 {id:'arr-positive',difficulty:'beginner',category:'Arrays',title:'Count Positive Values',statement:'Count how many values in the array are strictly greater than zero.',input:'An array of integers.',output:'The number of positive values.',constraints:'0 ≤ n ≤ 2000.',make(){const a=Array.from({length:randInt(0,14)},()=>randInt(-20,20));return {input:a,output:a.filter(x=>x>0).length}},js:`function solve(arr) {\n  let count = 0;\n  for (const x of arr) {\n    if (x > 0) count++;\n  }\n  return count;\n}`,py:`def solve(arr):\n    count = 0\n    for x in arr:\n        if x > 0: count += 1\n    return count`},
 {id:'str-reverse',difficulty:'beginner',category:'Strings',title:'Reverse the Text',statement:'Return the supplied lowercase string reversed.',input:'A lowercase string.',output:'The reversed string.',constraints:'0 ≤ length ≤ 500.',make(){const words=['debug','battle','array','python','compiler','practice','review','syntax','logic','coding'];const w=words[randInt(0,words.length-1)]+(Math.random()<.5?'':String.fromCharCode(97+randInt(0,25)));return {input:w,output:[...w].reverse().join('')}},js:`function solve(s) {\n  return [...s].reverse().join('');\n}`,py:`def solve(s):\n    return s[::-1]`},
 {id:'str-vowels',difficulty:'beginner',category:'Strings',title:'Count the Vowels',statement:'Return how many lowercase vowels (a, e, i, o, u) occur in the string.',input:'A lowercase string.',output:'The number of vowels.',constraints:'0 ≤ length ≤ 500.',make(){const words=['rhythm','education','algorithm','debugging','compiler','array','practice','strength','queue'];const w=words[randInt(0,words.length-1)];return {input:w,output:[...w].filter(ch=>'aeiou'.includes(ch)).length}},js:`function solve(s) {\n  let count = 0;\n  for (const ch of s) {\n    if ('aeiou'.includes(ch)) count++;\n  }\n  return count;\n}`,py:`def solve(s):\n    return sum(1 for ch in s if ch in 'aeiou')`},
 {id:'arr-distinct',difficulty:'beginner',category:'Arrays',title:'Count Distinct Values',statement:'Return the number of different integers that appear in the array.',input:'An array of integers.',output:'The number of distinct values.',constraints:'0 ≤ n ≤ 2000.',make(){const a=Array.from({length:randInt(0,14)},()=>randInt(-8,8));return {input:a,output:new Set(a).size}},js:`function solve(arr) {\n  return new Set(arr).size;\n}`,py:`def solve(arr):\n    return len(set(arr))`},
 {id:'arr-two-sum',difficulty:'intermediate',category:'Searching',title:'Pair Target',statement:'Return true if two different positions in the array contain values whose sum equals target; otherwise return false.',input:'An object {arr, target}.',output:'true or false.',constraints:'0 ≤ n ≤ 2000; values and target are integers.',make(){const a=Array.from({length:randInt(0,12)},()=>randInt(-20,20));const target=randInt(-25,25);return {input:{arr:a,target},output:(()=>{const seen=new Set();for(const x of a){if(seen.has(target-x))return true;seen.add(x)}return false})()}},js:`function solve(data) {\n  const seen = new Set();\n  for (const x of data.arr) {\n    if (seen.has(data.target - x)) return true;\n    seen.add(x);\n  }\n  return false;\n}`,py:`def solve(data):\n    seen = set()\n    for x in data['arr']:\n        if data['target'] - x in seen: return True\n        seen.add(x)\n    return False`},
 {id:'arr-rotate',difficulty:'intermediate',category:'Arrays',title:'Rotate the Array',statement:'Rotate the array to the right by k positions and return the resulting array.',input:'An object {arr, k}.',output:'The rotated array.',constraints:'0 ≤ n ≤ 1000; 0 ≤ k ≤ 10^6.',make(){const a=Array.from({length:randInt(0,10)},()=>randInt(-20,20));const k=randInt(0,20);const r=a.length?k%a.length:0;return {input:{arr:a,k},output:a.length?(r?a.slice(-r).concat(a.slice(0,-r)):a.slice()):[]}},js:`function solve(data) {\n  const a = data.arr;\n  if (a.length === 0) return [];\n  const k = data.k % a.length;\n  return k ? a.slice(-k).concat(a.slice(0, -k)) : a.slice();\n}`,py:`def solve(data):\n    a=data['arr']\n    if not a: return []\n    k=data['k']%len(a)\n    return a[-k:]+a[:-k] if k else a[:]`},
 {id:'str-frequency',difficulty:'intermediate',category:'Strings',title:'Most Common Letter',statement:'Return the lowercase letter with the highest frequency. If there is a tie, return the alphabetically earliest tied letter. Return an empty string for empty input.',input:'A lowercase string.',output:'One lowercase letter, or an empty string.',constraints:'0 ≤ length ≤ 5000.',make(){const pool=['banana','debugging','committee','mississippi','algorithm','abracadabra','bookkeeper'];const s=pool[randInt(0,pool.length-1)];const f={};for(const ch of s)f[ch]=(f[ch]||0)+1;let best='';for(const ch of Object.keys(f).sort()){if(!best||f[ch]>f[best])best=ch}return {input:s,output:best}},js:`function solve(s) {\n  if (!s.length) return '';\n  const f = {};\n  for (const ch of s) f[ch] = (f[ch] || 0) + 1;\n  let best = '';\n  for (const ch of Object.keys(f).sort()) {\n    if (!best || f[ch] > f[best]) best = ch;\n  }\n  return best;\n}`,py:`def solve(s):\n    if not s: return ''\n    f={}\n    for ch in s: f[ch]=f.get(ch,0)+1\n    best=''\n    for ch in sorted(f):\n        if not best or f[ch]>f[best]: best=ch\n    return best`},
 {id:'arr-prefix',difficulty:'intermediate',category:'Prefix Sums',title:'Prefix Totals',statement:'Return an array where each position contains the sum of all values from the start through that position.',input:'An array of integers.',output:'An array of prefix sums.',constraints:'0 ≤ n ≤ 5000.',make(){const a=Array.from({length:randInt(0,10)},()=>randInt(-20,20));let t=0;const o=a.map(x=>t+=x);return {input:a,output:o}},js:`function solve(arr) {\n  let total = 0;\n  const out = [];\n  for (const x of arr) {\n    total += x;\n    out.push(total);\n  }\n  return out;\n}`,py:`def solve(arr):\n    total=0; out=[]\n    for x in arr:\n        total+=x; out.append(total)\n    return out`},
 {id:'search-first',difficulty:'intermediate',category:'Searching',title:'First Matching Position',statement:'Return the first index where the value equals target, or -1 if target does not occur.',input:'An object {arr, target}.',output:'The first matching index, or -1.',constraints:'0 ≤ n ≤ 5000.',make(){const a=Array.from({length:randInt(0,12)},()=>randInt(-5,5));const target=randInt(-5,5);return {input:{arr:a,target},output:a.indexOf(target)}},js:`function solve(data) {\n  for (let i = 0; i < data.arr.length; i++) {\n    if (data.arr[i] === data.target) return i;\n  }\n  return -1;\n}`,py:`def solve(data):\n    for i,x in enumerate(data['arr']):\n        if x==data['target']: return i\n    return -1`},
 {id:'stack-brackets',difficulty:'intermediate',category:'Stacks',title:'Balanced Brackets',statement:'Return true when every (), [], and {} bracket is correctly opened and closed.',input:'A string containing brackets and lowercase letters.',output:'true or false.',constraints:'0 ≤ length ≤ 5000.',make(){const samples=['()[]{}','([{}])','(]','([)]','hello','{[()]}','((()))','{abc]'];const s=samples[randInt(0,samples.length-1)];const st=[];const pairs={')':'(',']':'[','}':'{'};let ok=true;for(const ch of s){if('([{'.includes(ch))st.push(ch);else if(pairs[ch]&&(st.pop()!==pairs[ch])){ok=false;break}}if(st.length)ok=false;return {input:s,output:ok}},js:`function solve(s) {\n  const st = [];\n  const pairs = {')':'(', ']':'[', '}':'{'};\n  for (const ch of s) {\n    if ('([{'.includes(ch)) st.push(ch);\n    else if (pairs[ch] && st.pop() !== pairs[ch]) return false;\n  }\n  return st.length === 0;\n}`,py:`def solve(s):\n    st=[]; pairs={')':'(',']':'[','}':'{'}\n    for ch in s:\n        if ch in '([{': st.append(ch)\n        elif ch in pairs and (not st or st.pop()!=pairs[ch]): return False\n    return not st`},
 {id:'arr-maxrun',difficulty:'advanced',category:'Algorithms',title:'Longest Rising Run',statement:'Return the length of the longest contiguous strictly increasing run.',input:'An array of integers.',output:'The maximum run length.',constraints:'0 ≤ n ≤ 100000.',make(){const a=Array.from({length:randInt(0,18)},()=>randInt(-40,40));let best=a.length?1:0,run=best;for(let i=1;i<a.length;i++){run=a[i]>a[i-1]?run+1:1;best=Math.max(best,run)}return {input:a,output:best}},js:`function solve(arr) {\n  if (arr.length === 0) return 0;\n  let best = 1, run = 1;\n  for (let i = 1; i < arr.length; i++) {\n    run = arr[i] > arr[i - 1] ? run + 1 : 1;\n    best = Math.max(best, run);\n  }\n  return best;\n}`,py:`def solve(arr):\n    if not arr: return 0\n    best=run=1\n    for i in range(1,len(arr)):\n        run=run+1 if arr[i]>arr[i-1] else 1\n        best=max(best,run)\n    return best`},
 {id:'arr-maxsub',difficulty:'advanced',category:'Dynamic Programming',title:'Best Contiguous Sum',statement:'Return the largest possible sum of a non-empty contiguous subarray.',input:'An array of integers.',output:'The maximum contiguous sum.',constraints:'1 ≤ n ≤ 100000.',make(){const a=Array.from({length:randInt(1,16)},()=>randInt(-30,30));let best=a[0],cur=a[0];for(let i=1;i<a.length;i++){cur=Math.max(a[i],cur+a[i]);best=Math.max(best,cur)}return {input:a,output:best}},js:`function solve(arr) {\n  let cur = arr[0], best = arr[0];\n  for (let i = 1; i < arr.length; i++) {\n    cur = Math.max(arr[i], cur + arr[i]);\n    best = Math.max(best, cur);\n  }\n  return best;\n}`,py:`def solve(arr):\n    cur=best=arr[0]\n    for x in arr[1:]:\n        cur=max(x,cur+x); best=max(best,cur)\n    return best`},
 {id:'arr-dedup-sorted',difficulty:'advanced',category:'Two Pointers',title:'Compact Sorted Values',statement:'Given a sorted integer array, return a new array containing each value only once, preserving sorted order.',input:'A sorted array of integers.',output:'The deduplicated sorted array.',constraints:'0 ≤ n ≤ 100000.',make(){const a=Array.from({length:randInt(0,18)},()=>randInt(-5,8)).sort((x,y)=>x-y);return {input:a,output:[...new Set(a)]}},js:`function solve(arr) {\n  if (arr.length === 0) return [];\n  const out = [arr[0]];\n  for (let i = 1; i < arr.length; i++) {\n    if (arr[i] !== arr[i - 1]) out.push(arr[i]);\n  }\n  return out;\n}`,py:`def solve(arr):\n    if not arr: return []\n    out=[arr[0]]\n    for x in arr[1:]:\n        if x!=out[-1]: out.append(x)\n    return out`},
 {id:'arr-window',difficulty:'advanced',category:'Sliding Window',title:'Best Window',statement:'Return the maximum sum of any contiguous block of exactly k elements.',input:'An object {arr, k}.',output:'The maximum window sum.',constraints:'1 ≤ k ≤ n ≤ 100000.',make(){const a=Array.from({length:randInt(1,16)},()=>randInt(-20,30));const k=randInt(1,a.length);let sum=0;for(let i=0;i<k;i++)sum+=a[i];let best=sum;for(let i=k;i<a.length;i++){sum+=a[i]-a[i-k];best=Math.max(best,sum)}return {input:{arr:a,k},output:best}},js:`function solve(data) {\n  const a = data.arr, k = data.k;\n  let sum = 0;\n  for (let i = 0; i < k; i++) sum += a[i];\n  let best = sum;\n  for (let i = k; i < a.length; i++) {\n    sum += a[i] - a[i - k];\n    best = Math.max(best, sum);\n  }\n  return best;\n}`,py:`def solve(data):\n    a,k=data['arr'],data['k']; total=sum(a[:k]); best=total\n    for i in range(k,len(a)):\n        total+=a[i]-a[i-k]; best=max(best,total)\n    return best`}
];
const proceduralByDifficulty = Object.fromEntries(['beginner','intermediate','advanced'].map(d=>[d,proceduralTemplates.filter(t=>t.difficulty===d)]));
function makeProceduralChallenge(t,language,difficulty){
 const cases=Array.from({length:9},()=>t.make());
 const seed=crypto.randomBytes(8).toString('hex');
 const c={id:`gen-${t.id}-${seed}`,title:t.title,category:t.category,difficulty,language,problem:t.statement,input:t.input,output:t.output,constraints:t.constraints,exampleInput:JSON.stringify(cases[0].input),exampleOutput:JSON.stringify(cases[0].output),referenceSolution:language==='python'?t.py:t.js,tests:cases.slice(0,3).map((x,i)=>({name:`case-${i+1}`,input:JSON.stringify(x.input),output:JSON.stringify(x.output)})),hidden:cases.slice(3).map((x,i)=>({name:`hidden-${i+1}`,input:JSON.stringify(x.input),output:JSON.stringify(x.output)}))};
 // Small wording variation prevents identical statements from feeling like a fixed quiz.
 const prefixes=['Solve this challenge: ','Your task: ','Challenge: ','Implement a function that will '];
 c.problem=prefixes[randInt(0,prefixes.length-1)]+t.statement.charAt(0).toLowerCase()+t.statement.slice(1);
 challengeStore.set(c.id,c); return c;
}

const challengeStore=new Map(challenges.map(c=>[c.id,c]));
const now=()=>Date.now();const sessions=new Map();const games=new Map();const queues=new Map();const rooms=new Map();
function uid(){return crypto.randomUUID()}function publicChallenge(c,lang){return {...c,referenceSolution:undefined,hidden:undefined,referenceSolution:undefined,language:lang,referenceSolution:undefined,tests:c.tests}}
function getUser(req){const token=req.cookies?.cb_session;if(!token)return null;const s=db.prepare('SELECT * FROM Sessions WHERE token=?').get(token);if(!s||s.expires_at<now()){return null}const u=db.prepare('SELECT id,username,is_admin FROM Users WHERE id=?').get(s.user_id);if(u)return {...u,is_admin:!!u.is_admin};const g=db.prepare('SELECT id,guest_id FROM GuestSessions WHERE id=?').get(s.user_id);return g?{id:g.id,username:g.guest_id,guest:true}:null}
function auth(req,res,next){const u=getUser(req);if(!u)return res.status(401).json({error:'Authentication required'});req.user=u;next()}
function createSession(res,userId){const token=crypto.randomBytes(32).toString('hex');db.prepare('INSERT INTO Sessions VALUES(?,?,?)').run(token,userId,now()+1000*60*60*24*30);res.cookie('cb_session',token,{httpOnly:true,sameSite:'lax',secure:false,maxAge:1000*60*60*24*30});}
(async()=>{try{const admin=db.prepare('SELECT id FROM Users WHERE username=?').get('admin');if(!admin){const id=uid();const hash=await bcrypt.hash(process.env.ADMIN_PASSWORD||'CodeBattleAdmin123!',12);db.prepare('INSERT INTO Users(id,username,password_hash,created_at,is_admin) VALUES(?,?,?,?,0)').run(id,'admin',hash,now());for(const d of ['beginner','intermediate','advanced'])db.prepare('INSERT INTO Leaderboard VALUES(?,?,0,0)').run(id,d)}}catch(e){console.error('Admin bootstrap failed:',e.message)}})();
app.post('/api/register',async(req,res)=>{try{const {username,password}=req.body;if(username==='admin')return res.status(409).json({error:'The admin username is reserved.'});if(!/^[a-zA-Z0-9_]{3,24}$/.test(username))return res.status(400).json({error:'Username must be 3–24 letters, numbers or underscores.'});if(!password||password.length<8)return res.status(400).json({error:'Password must be at least 8 characters.'});const id=uid();const hash=await bcrypt.hash(password,12);db.prepare('INSERT INTO Users(id,username,password_hash,created_at,is_admin) VALUES(?,?,?,?,?)').run(id,username,hash,now(),username==='admin'?1:0);for(const d of ['beginner','intermediate','advanced'])db.prepare('INSERT INTO Leaderboard VALUES(?,?,0,0)').run(id,d);createSession(res,id);res.json({user:{id,username,is_admin:username==='admin'}})}catch(e){res.status(409).json({error:'Username already exists.'})}});
app.post('/api/login',async(req,res)=>{const u=db.prepare('SELECT * FROM Users WHERE username=?').get(req.body.username);if(!u||!(await bcrypt.compare(req.body.password||'',u.password_hash)))return res.status(401).json({error:'Invalid username or password.'});createSession(res,u.id);res.json({user:{id:u.id,username:u.username,is_admin:!!u.is_admin}})});
app.post('/api/guest',(req,res)=>{const id=uid(),guest='Guest-'+crypto.randomBytes(3).toString('hex').toUpperCase();db.prepare('INSERT INTO GuestSessions VALUES(?,?,?,?)').run(id,guest,now(),now()+1000*60*60*24*7);createSession(res,id);res.json({user:{id,username:guest,guest:true}})});
app.post('/api/logout',(req,res)=>{const t=req.cookies?.cb_session;if(t)db.prepare('DELETE FROM Sessions WHERE token=?').run(t);res.clearCookie('cb_session');res.json({ok:true})});app.get('/api/me',(req,res)=>res.json({user:getUser(req)}));

function requireAdmin(req,res,next){
 const u=req.user;
 if(!u||u.guest||(!u.is_admin && u.username!=='admin')) return res.status(403).json({error:'Admin access required.'});
 req.admin=u; next();
}
app.post('/api/feedback',auth,(req,res)=>{
 const u=req.user;if(!u||u.guest)return res.status(401).json({error:'Please register or log in to submit feedback.'});
 const type=String(req.body.type||'Other').trim();const subject=String(req.body.subject||'').trim();const description=String(req.body.description||'').trim();const gameId=req.body.game_id?String(req.body.game_id).trim():null;
 if(!['Bug Report','Feature Request','Game Issue','Other'].includes(type))return res.status(400).json({error:'Invalid feedback type.'});
 if(!subject||subject.length>120)return res.status(400).json({error:'Subject is required and must be 120 characters or fewer.'});
 if(!description||description.length>4000)return res.status(400).json({error:'Description is required and must be 4000 characters or fewer.'});
 const id=uid();db.prepare('INSERT INTO Feedback(id,user_id,username,type,subject,description,game_id,status,created_at) VALUES(?,?,?,?,?,?,?,?,?)').run(id,u.id,u.username,type,subject,description,gameId,'open',now());res.json({ok:true,id});
});
app.get('/api/admin/feedback',auth,requireAdmin,(req,res)=>{res.json({feedback:db.prepare('SELECT * FROM Feedback ORDER BY created_at DESC').all()})});
app.post('/api/admin/feedback/:id/status',auth,requireAdmin,(req,res)=>{const status=String(req.body.status||'');if(!['open','in_progress','resolved'].includes(status))return res.status(400).json({error:'Invalid feedback status.'});const r=db.prepare('UPDATE Feedback SET status=? WHERE id=?').run(status,req.params.id);if(!r.changes)return res.status(404).json({error:'Feedback not found.'});res.json({ok:true});});
app.get('/api/admin/summary',auth,requireAdmin,(req,res)=>{
 const users=db.prepare('SELECT COUNT(*) n FROM Users').get().n;
 const matches=db.prepare('SELECT COUNT(*) n FROM Matches').get().n;
 const ranked=db.prepare('SELECT COUNT(*) n FROM Matches WHERE ranked=1').get().n;
 const active=db.prepare("SELECT COUNT(*) n FROM Matches WHERE status='active'").get().n;
 res.json({users,matches,ranked,active});
});
app.get('/api/admin/users',auth,requireAdmin,(req,res)=>{
 const rows=db.prepare(`SELECT u.id,u.username,u.created_at,u.is_admin,
   COALESCE((SELECT SUM(points) FROM Leaderboard l WHERE l.user_id=u.id),0) points,
   COALESCE((SELECT SUM(wins) FROM Leaderboard l WHERE l.user_id=u.id),0) wins
   FROM Users u ORDER BY u.username COLLATE NOCASE`).all();
 res.json({users:rows.map(x=>({...x,is_admin:!!x.is_admin}))});
});
app.post('/api/admin/users/:id/password',auth,requireAdmin,async(req,res)=>{
 const password=String(req.body.password||'');
 if(password.length<8)return res.status(400).json({error:'Password must be at least 8 characters.'});
 const target=db.prepare('SELECT id,username FROM Users WHERE id=?').get(req.params.id);
 if(!target)return res.status(404).json({error:'User not found.'});
 if(target.username==='admin' && req.admin.username!=='admin')return res.status(403).json({error:'Only the primary admin can change the primary admin password.'});
 const hash=await bcrypt.hash(password,12);
 db.prepare('UPDATE Users SET password_hash=? WHERE id=?').run(hash,target.id);
 db.prepare('DELETE FROM Sessions WHERE user_id=?').run(target.id);
 res.json({ok:true});
});
app.post('/api/admin/users/:id/admin',auth,requireAdmin,(req,res)=>{
 const target=db.prepare('SELECT id,username FROM Users WHERE id=?').get(req.params.id);
 if(!target)return res.status(404).json({error:'User not found.'});
 if(target.username==='admin' && !req.body.enabled) return res.status(400).json({error:'The admin account cannot lose its admin permission.'});
 db.prepare('UPDATE Users SET is_admin=? WHERE id=?').run(req.body.enabled?1:0,target.id);
 res.json({ok:true,is_admin:!!req.body.enabled});
});
app.post('/api/admin/users/:id/leaderboard',auth,requireAdmin,(req,res)=>{
 const target=db.prepare('SELECT id,username FROM Users WHERE id=?').get(req.params.id);
 if(!target)return res.status(404).json({error:'User not found.'});
 const d=['beginner','intermediate','advanced'].includes(req.body.difficulty)?req.body.difficulty:null;
 const points=Number(req.body.points),wins=Number(req.body.wins);
 if(!d||!Number.isInteger(points)||!Number.isInteger(wins)||points<0||wins<0)return res.status(400).json({error:'Invalid difficulty, points or wins.'});
 db.prepare('INSERT INTO Leaderboard(user_id,difficulty,points,wins) VALUES(?,?,?,?) ON CONFLICT(user_id,difficulty) DO UPDATE SET points=?,wins=?').run(target.id,d,points,wins,points,wins);
 res.json({ok:true});
});
app.post('/api/admin/users/:id/reset-stats',auth,requireAdmin,(req,res)=>{
 const target=db.prepare('SELECT id FROM Users WHERE id=?').get(req.params.id);
 if(!target)return res.status(404).json({error:'User not found.'});
 db.prepare('UPDATE Leaderboard SET points=0,wins=0 WHERE user_id=?').run(target.id);
 db.prepare('DELETE FROM Matches WHERE player1=? OR player2=?').run(target.id,target.id);
 res.json({ok:true});
});
app.delete('/api/admin/users/:id',auth,requireAdmin,(req,res)=>{
 const target=db.prepare('SELECT id,username FROM Users WHERE id=?').get(req.params.id);
 if(!target)return res.status(404).json({error:'User not found.'});
 if(target.username==='admin' || target.id===req.admin.id)return res.status(400).json({error:'The primary admin account cannot be deleted.'});
 db.prepare('DELETE FROM Sessions WHERE user_id=?').run(target.id);
 db.prepare('DELETE FROM Leaderboard WHERE user_id=?').run(target.id);
 db.prepare('DELETE FROM Users WHERE id=?').run(target.id);
 res.json({ok:true});
});
app.get('/api/stats/:id',(req,res)=>{const u=db.prepare('SELECT id,username,is_admin FROM Users WHERE id=?').get(req.params.id);if(!u)return res.json({points:0,wins:0,matches:0});const rows=db.prepare('SELECT * FROM Leaderboard WHERE user_id=?').all(u.id);const points=rows.reduce((a,b)=>a+b.points,0),wins=rows.reduce((a,b)=>a+b.wins,0);const matches=db.prepare('SELECT COUNT(*) n FROM Matches WHERE (player1=? OR player2=?)').get(u.id,u.id).n;const best=rows.sort((a,b)=>b.points-a.points)[0]?.difficulty||'—';res.json({points,wins,matches,bestDifficulty:best})});
app.get('/api/leaderboard',(req,res)=>{const d=['beginner','intermediate','advanced'].includes(req.query.difficulty)?req.query.difficulty:null;const sql=d?`SELECT u.username,l.difficulty,l.points,l.wins FROM Leaderboard l JOIN Users u ON u.id=l.user_id WHERE l.points>0 AND l.difficulty=? ORDER BY l.points DESC,l.wins DESC LIMIT 100`:`SELECT u.username,l.difficulty,l.points,l.wins FROM Leaderboard l JOIN Users u ON u.id=l.user_id WHERE l.points>0 ORDER BY l.points DESC,l.wins DESC LIMIT 100`;res.json(d?db.prepare(sql).all(d):db.prepare(sql).all())});
app.get('/api/practice',(req,res)=>{const {language='javascript',difficulty='beginner'}=req.query;const c=pickChallenge(language,difficulty);const out={...c};delete out.hidden;res.json({challenge:out})});
function safeJson(s){try{return JSON.stringify(JSON.parse(s))}catch{return JSON.stringify(s)}}
function execute(language,code,input,timeout=2500){return new Promise(resolve=>{const dir=fs.mkdtempSync(path.join(require('os').tmpdir(),'cb-'));let file,cmd,args;const runner=`const fs=require('fs');const input=fs.readFileSync(0,'utf8');let data;try{data=JSON.parse(input)}catch{data=input};\n${code}\nPromise.resolve(solve(data)).then(v=>process.stdout.write(JSON.stringify(v))).catch(e=>{console.error(e.message);process.exit(2)});`;if(language==='javascript'){file=path.join(dir,'main.js');fs.writeFileSync(file,runner);cmd=process.execPath;args=[file]}else{file=path.join(dir,'main.py');const py=`import sys,json\n${code}\nraw=sys.stdin.read()\ntry: data=json.loads(raw)\nexcept: data=raw\ntry: print(json.dumps(solve(data),separators=(',',':')))\nexcept Exception as e:\n print(str(e),file=sys.stderr);sys.exit(2)`;fs.writeFileSync(file,py);cmd=process.platform==='win32'?'python':'python3';args=[file]}let out='',err='';const p=spawn(cmd,args,{cwd:dir,stdio:['pipe','pipe','pipe']});p.stdout.on('data',d=>out+=d);p.stderr.on('data',d=>err+=d);const kill=setTimeout(()=>{p.kill('SIGKILL');resolve({ok:false,error:'Execution timed out'});fs.rmSync(dir,{recursive:true,force:true})},timeout);p.on('close',()=>{clearTimeout(kill);const result={ok:p.exitCode===0,output:out.trim(),error:err.trim()};fs.rmSync(dir,{recursive:true,force:true});resolve(result) });p.stdin.end(input);})}
async function runTests(c,language,code,hidden){const all=(hidden?c.hidden:c.tests)||[];const results=[];for(const t of all){const r=await execute(language,code,t.input);const expected=safeJson(t.output);const pass=r.ok&&r.output===expected;results.push({name:t.name,pass,message:pass?'Passed':r.error||`Expected ${expected}, got ${r.output||'<no output>'}`});if(!pass&&hidden){} }return results}
app.post('/api/execute',async(req,res)=>{const {challengeId,language,code,publicOnly=false}=req.body;const c=challengeStore.get(challengeId)||challenges.find(x=>x.id===challengeId);if(!c)return res.status(404).json({error:'Challenge not found'});const results=await runTests(c,language,code,!publicOnly);res.json({tests:results,passed:results.every(x=>x.pass)});});
function diffChangedLines(a,b){const A=a.split('\n'),B=b.split('\n');let i=0,j=0,changed=new Set();while(i<A.length&&j<B.length){if(A[i]===B[j]){i++;j++;continue}changed.add(i+1);i++;j++;}while(i<A.length){changed.add(i+1);i++}while(j<B.length){changed.add(Math.max(1,i));j++}return changed.size}
function randInt(a,b){return Math.floor(Math.random()*(b-a+1))+a}
function pickChallenge(language,difficulty,used=[]){const procedural=proceduralByDifficulty[difficulty]||[];const useProcedural=procedural.length>0;if(useProcedural){return makeProceduralChallenge(procedural[randInt(0,procedural.length-1)],language,difficulty)}const pool=challenges.filter(c=>c.difficulty===difficulty);const fresh=pool.filter(c=>!used.includes(c.id));const base=(fresh.length?fresh:pool)[randInt(0,(fresh.length?fresh:pool).length-1)];return generateVariant(base,language,difficulty)}
function generateVariant(base,language,difficulty){const c=language==='python'?{...base,language:'python',referenceSolution:pyEquivalent[base.id]}:{...base};c.id=`${base.id}-v${crypto.randomBytes(4).toString('hex')}`;
if(base.id==='js-beg-arr'){const make=()=>Array.from({length:randInt(0,difficulty==='advanced'?14:9)},()=>randInt(-50,50));const arrays=Array.from({length:7},make);const sum=a=>a.reduce((x,y)=>x+y,0);c.title=['Repair the Total','Restore the Array Sum','Array Sum Audit'][randInt(0,2)];c.problem=['Return the sum of every integer in the supplied array. Empty arrays must return 0.','Calculate the total of all values in an integer array, including negative values.','Audit an integer array and produce its arithmetic total; an empty array has total 0.'][randInt(0,2)];c.exampleInput=JSON.stringify(arrays[0]);c.exampleOutput=String(sum(arrays[0]));const ts=arrays.map((a,i)=>({name:`case-${i+1}`,input:JSON.stringify(a),output:String(sum(a))}));c.tests=ts.slice(0,3);c.hidden=ts.slice(3)}
else if(base.id==='js-beg-str'){const words=['debug','education','rhythm','algorithm','review','compiler','array','python','javascript','competition','learning'];const w=words[randInt(0,words.length-1)];const idx=[...w].findIndex(ch=>'aeiou'.includes(ch));c.title=['First Vowel','Vowel Detector','Locate the First Vowel'][randInt(0,2)];c.problem=['Return the zero-based position of the first lowercase vowel in the string, or -1 if none exists.','Scan the supplied lowercase text and report where its first vowel occurs. Return -1 when no vowel is present.','Find the earliest a/e/i/o/u in the string and return its index.'][randInt(0,2)];c.exampleInput=JSON.stringify(w);c.exampleOutput=String(idx);const ts=words.map((x,i)=>({name:`case-${i+1}`,input:JSON.stringify(x),output:String([...x].findIndex(ch=>'aeiou'.includes(ch)))}));c.tests=ts.slice(0,3);c.hidden=ts.slice(3)}
else if(base.id==='js-int-loop'){const ts=[];for(let i=0;i<7;i++){const a=Array.from({length:randInt(1,12)},()=>randInt(-40,40));ts.push({name:`case-${i+1}`,input:JSON.stringify(a),output:String(a.filter(x=>x%2===0).length)})}c.problem=['Count the even integers in the array. Zero and negative values are valid inputs.','Determine how many values are divisible by two.','Return the number of even elements in the supplied integer array.'][randInt(0,2)];c.exampleInput=ts[0].input;c.exampleOutput=ts[0].output;c.tests=ts.slice(0,3);c.hidden=ts.slice(3)}
else if(base.id==='js-int-search'){const ts=[];for(let i=0;i<7;i++){const a=Array.from({length:randInt(0,10)},()=>randInt(-30,30)).sort((x,y)=>x-y);const target=a.length&&Math.random()<.65?a[randInt(0,a.length-1)]:randInt(-30,30);let lo=0,hi=a.length-1,ans=-1;while(lo<=hi){const m=Math.floor((lo+hi)/2);if(a[m]===target){ans=m;break}if(a[m]<target)lo=m+1;else hi=m-1}ts.push({name:`case-${i+1}`,input:JSON.stringify({arr:a,target}),output:String(ans)})}c.problem=['Find the index of target in the sorted array using binary search; return -1 if absent.','Search the ordered array efficiently and return the target position, or -1 when it is not present.','Locate a target in ascending order data using binary search.'][randInt(0,2)];c.exampleInput=ts[0].input;c.exampleOutput=ts[0].output;c.tests=ts.slice(0,3);c.hidden=ts.slice(3)}
else if(base.id==='js-adv-math'){const ts=[];for(let i=0;i<7;i++){const a=Array.from({length:randInt(0,14)},()=>randInt(-30,40));let best=a.length?1:0,run=best;for(let j=1;j<a.length;j++){run=a[j]>a[j-1]?run+1:1;best=Math.max(best,run)}ts.push({name:`case-${i+1}`,input:JSON.stringify(a),output:String(best)})}c.problem=['Return the length of the longest contiguous strictly increasing run. Equal adjacent values break a run.','Measure the longest adjacent chain where every next number is greater than the previous one.','Find the maximum length of a strictly rising contiguous segment.'][randInt(0,2)];c.exampleInput=ts[0].input;c.exampleOutput=ts[0].output;c.tests=ts.slice(0,3);c.hidden=ts.slice(3)}
challengeStore.set(c.id,c);return c}
function phaseGame(g){g.phase='sabotage';g.phaseLabel='SABOTAGE';g.phaseEndsAt=now()+g.sabotageSeconds*1000;g.challenge=publicChallenge(g.challenge,g.language);broadcast(g)}
function broadcast(g){for(const p of g.players){if(p.socketId)io.to(p.socketId).emit('game:state',sanitizeGame(g,p.id))}}
function sanitizeGame(g,viewerId){const role=g.roles?.[viewerId];const canSeeCode=role==='saboteur'||g.phase!=='sabotage';return {matchId:g.id,ranked:!!g.ranked,players:g.players.map(p=>({id:p.id,username:p.username})),opponentId:g.players.find(p=>p.id!==viewerId)?.id,roles:g.roles,scores:g.scores,roundNumber:g.roundNumber,phase:g.phase,phaseLabel:g.phaseLabel,phaseEndsAt:g.phaseEndsAt,challenge:{id:g.challenge.id,title:g.challenge.title,problem:g.challenge.problem,input:g.challenge.input,output:g.challenge.output,constraints:g.challenge.constraints,exampleInput:g.challenge.exampleInput,exampleOutput:g.challenge.exampleOutput},code:canSeeCode?g.currentCode:'',maxChanges:g.maxChanges,language:g.language,difficulty:g.difficulty,winnerId:g.winnerId,resultMessage:g.resultMessage};}
function randomChangeLimit(difficulty){return Math.random()<0.5?1:2}

function beginGame(id){const g=games.get(id);g.usedChallenges=[];g.challenge=g.custom||pickChallenge(g.language,g.difficulty,g.usedChallenges);if(!g.custom)g.usedChallenges.push(g.challenge.id.split('-v')[0]);g.roles=g.botId?{[g.players[0].id]:'debugger',[g.botId]:'saboteur'}:{[g.players[0].id]:'saboteur',[g.players[1].id]:'debugger'};g.scores={[g.players[0].id]:g.scores[g.players[0].id]||0,[g.players[1].id]:g.scores[g.players[1].id]||0};g.roundNumber=g.roundNumber||1;g.currentCode=g.challenge.referenceSolution;g.originalCode=g.challenge.referenceSolution;g.sabotageSeconds=g.sabotageSeconds||45;g.debugSeconds=g.debugSeconds||180;g.maxChanges=randomChangeLimit(g.difficulty);g.phase='sabotage';g.phaseLabel='SABOTAGE';g.phaseEndsAt=now()+g.sabotageSeconds*1000;db.prepare('INSERT INTO Rounds VALUES(?,?,?,?,?,?,?)').run(uid(),g.id,g.roundNumber,Object.entries(g.roles).find(([,r])=>r==='saboteur')[0],Object.entries(g.roles).find(([,r])=>r==='debugger')[0],g.challenge.id,null);for(const p of g.players){if(p.socketId)io.to(p.socketId).emit('match:found',sanitizeGame(g,p.id));}broadcast(g)}
function createGame(players,opts,ranked=false,extra={}){const id=uid();const g={id,players,botId:extra.botId||null,botSkill:extra.botSkill||opts.difficulty,language:opts.language,difficulty:opts.difficulty,custom:opts.custom||null,ranked,roundNumber:1,scores:{},sabotageSeconds:opts.sabotageSeconds||45,debugSeconds:opts.debugSeconds||180,maxChanges:opts.maxChanges||3};games.set(id,g);for(const p of players)io.sockets.sockets.get(p.socketId)?.join(id);beginGame(id);return g}
function nextRound(g){if(g.scores[g.players[0].id]>=3||g.scores[g.players[1].id]>=3){finishMatch(g);return}g.roundNumber++;const ids=g.players.map(p=>p.id);g.roles={[ids[0]]:g.roles[ids[1]]==='saboteur'?'saboteur':'debugger',[ids[1]]:g.roles[ids[0]]==='saboteur'?'saboteur':'debugger'};g.challenge=pickChallenge(g.language,g.difficulty,g.usedChallenges||[]);g.usedChallenges=g.usedChallenges||[];g.usedChallenges.push(g.challenge.id.split('-v')[0]);g.originalCode=g.challenge.referenceSolution;g.currentCode=g.originalCode;g.phase='sabotage';g.phaseLabel='SABOTAGE';g.phaseEndsAt=now()+g.sabotageSeconds*1000;db.prepare('INSERT INTO Rounds VALUES(?,?,?,?,?,?,?)').run(uid(),g.id,g.roundNumber,Object.entries(g.roles).find(([,r])=>r==='saboteur')[0],Object.entries(g.roles).find(([,r])=>r==='debugger')[0],g.challenge.id,null);broadcast(g);if(g.botId&&g.roles[g.botId]==='saboteur')setTimeout(()=>botSabotage(g),900)}
function finishMatch(g){g.phase='ended';g.phaseLabel='MATCH COMPLETE';if(!g.winnerId)g.winnerId=g.scores[g.players[0].id]>g.scores[g.players[1].id]?g.players[0].id:g.players[1].id;g.resultMessage=g.resultMessage||'Match complete';db.prepare('UPDATE Matches SET status=?,winner=? WHERE id=?').run('complete',g.winnerId,g.id);if(g.ranked){const winner=g.winnerId;const wu=g.players.find(p=>p.id===winner);if(wu&&!wu.guest){db.prepare('INSERT INTO Leaderboard(user_id,difficulty,points,wins) VALUES(?,?,1,1) ON CONFLICT(user_id,difficulty) DO UPDATE SET points=points+1,wins=wins+1').run(winner,g.difficulty)}}broadcast(g);io.to(g.id).emit('match:ended',sanitizeGame(g))}
setInterval(async()=>{for(const g of games.values()){if(g.phase==='ended')continue;if(now()>=g.phaseEndsAt){if(g.phase==='sabotage'){g.currentCode=g.currentCode||g.originalCode;g.phase='debug';g.phaseLabel='DEBUG';g.phaseEndsAt=now()+g.debugSeconds*1000;broadcast(g);if(g.botId&&g.roles[g.botId]==='debugger')botDebug(g)}else if(g.phase==='debug'){g.resultMessage='Debugger ran out of time.';const sab=Object.entries(g.roles).find(([,r])=>r==='saboteur')[0];g.scores[sab]=(g.scores[sab]||0)+1;g.result='saboteur';db.prepare('UPDATE Rounds SET result=? WHERE match_id=? AND round_number=?').run('saboteur',g.id,g.roundNumber);broadcast(g);setTimeout(()=>nextRound(g),1500)}}}},250);
io.use((socket,next)=>{const cookie=socket.handshake.headers.cookie||'';const m=cookie.match(/cb_session=([^;]+)/);if(!m)return next(new Error('Not authenticated'));const s=db.prepare('SELECT * FROM Sessions WHERE token=?').get(m[1]);if(!s||s.expires_at<now())return next(new Error('Session expired'));let u=db.prepare('SELECT id,username,is_admin FROM Users WHERE id=?').get(s.user_id);if(!u){const g=db.prepare('SELECT id,guest_id FROM GuestSessions WHERE id=?').get(s.user_id);if(g)u={id:g.id,username:g.guest_id,guest:true}}if(!u)return next(new Error('User missing'));socket.user=u;next()});
async function botSabotage(g){if(g.phase!=='sabotage'||g.roles[g.botId]!=='saboteur')return;const lines=g.originalCode.split('\n');const candidates=[];for(let i=0;i<lines.length;i++){const l=lines[i];if(/===|>|<|\+\+|--|return|\+=|-=|%/.test(l))candidates.push(i)}let count=Math.min(g.maxChanges,1+(Math.random()<.35?1:0));let used=new Set();for(let k=0;k<count;k++){let i=candidates.filter(x=>!used.has(x))[randInt(0,Math.max(0,candidates.filter(x=>!used.has(x)).length-1))];if(i==null)break;used.add(i);lines[i]=sabotageLine(lines[i],g.language,g.botSkill)}g.currentCode=lines.join('\n');setTimeout(()=>lockSabotage(g,g.currentCode),1200+randInt(300,1800))}
function sabotageLine(line,language,skill){if(language==='javascript'){if(line.includes('==='))return line.replace('===','!==');if(line.includes('>'))return line.replace('>','>=');if(line.includes('<'))return line.replace('<','<=');if(line.includes('++'))return line.replace('++','--');if(line.includes('+='))return line.replace('+=','-=');if(line.includes('return'))return line.replace(/return\s+([^;]+)/,'return 0');}else{if(line.includes('=='))return line.replace('==','!=');if(line.includes('>'))return line.replace('>','>=');if(line.includes('<'))return line.replace('<','<=');if(line.includes('+='))return line.replace('+=','-=');if(line.includes('return'))return line.replace(/return\s+(.+)/,'return 0')}return line}
function lockSabotage(g,source){if(g.phase!=='sabotage')return;g.currentCode=source;g.changedLines=diffChangedLines(g.originalCode,source);if(g.changedLines>g.maxChanges){g.currentCode=g.originalCode;return}g.phase='debug';g.phaseLabel='DEBUG';g.phaseEndsAt=now()+g.debugSeconds*1000;broadcast(g);if(g.botId&&g.roles[g.botId]==='debugger')botDebug(g)}
async function botDebug(g){if(g.phase!=='debug'||g.roles[g.botId]!=='debugger')return;const willWin=Math.random()>(g.botLoseChance||0.2);const delay=Math.min(g.debugSeconds*1000-500,willWin?(g.botSkill==='advanced'?randInt(5000,18000):g.botSkill==='intermediate'?randInt(7000,25000):randInt(9000,30000)):randInt(8000,Math.max(9000,g.debugSeconds*1000-1000)));setTimeout(async()=>{if(g.phase!=='debug')return;if(!willWin){g.resultMessage='CodeBot made an intentional mistake and lost the round.';const human=g.players.find(p=>p.id!==g.botId)?.id;g.scores[human]=(g.scores[human]||0)+1;g.phase='ended';g.phaseLabel='ROUND COMPLETE';broadcast(g);setTimeout(()=>nextRound(g),1400);return}const broken=g.currentCode.split('\n'),correct=g.originalCode.split('\n'),sab=g.players.find(p=>p.id!==g.botId);let step=0;const timer=setInterval(()=>{if(g.phase!=='debug'){clearInterval(timer);return}if(step>=correct.length){clearInterval(timer);g.currentCode=g.originalCode;g.scores[g.botId]=(g.scores[g.botId]||0)+1;g.resultMessage='CodeBot fixed the program.';g.phase='ended';g.phaseLabel='ROUND COMPLETE';broadcast(g);setTimeout(()=>nextRound(g),1400);return}const lineDiff=broken[step]!==correct[step];if(lineDiff){g.currentCode=correct.slice(0,step+1).concat(broken.slice(step+1)).join('\n');if(sab)io.to(sab.socketId).emit('game:liveCode',{source:g.currentCode})}step++},Math.max(180,Math.floor(delay/Math.max(1,correct.length))))},delay)}
io.on('connection',socket=>{
 socket.on('computer:start',opts=>{const human={id:socket.user.id,username:socket.user.username,socketId:socket.id};const botId='bot-'+uid();const bot={id:botId,username:'CodeBot',socketId:null,guest:true};const g=createGame([human,bot],opts,false,{botId,botSkill:opts.difficulty});g.botLoseChance=opts.difficulty==='beginner'?0.42:opts.difficulty==='intermediate'?0.28:0.18;broadcast(g);setTimeout(()=>botSabotage(g),900);});
 socket.on('queue:join',opts=>{if(opts.ranked&&socket.user.guest)return socket.emit('error:game',{message:'Ranked matches require a registered account so your points can be persisted.'});const key=`${opts.language}:${opts.difficulty}`;if(!queues.has(key))queues.set(key,[]);const q=queues.get(key);q.push({id:socket.user.id,username:socket.user.username,socketId:socket.id});socket.emit('matchmaking:waiting',opts);if(q.length>=2){const a=q.shift(),b=q.shift();db.prepare('INSERT INTO Matches VALUES(?,?,?,?,?,?,?,?,?)').run(uid(),a.id,b.id,opts.language,opts.difficulty,'active',null,opts.ranked?1:0,now());createGame([a,b],opts,!!opts.ranked)}});
 socket.on('queue:leave',()=>{for(const q of queues.values()){const i=q.findIndex(x=>x.id===socket.user.id);if(i>=0)q.splice(i,1)}});
 socket.on('room:create',async opts=>{let custom=null;if(opts.custom?.enabled){try{const tests=JSON.parse(opts.custom.tests||'[]');if(!opts.custom.title||!opts.custom.problem||!opts.custom.solution||!Array.isArray(tests)||!tests.length)throw Error('Custom challenge needs title, statement, solution and at least one test.');const cid='custom-'+uid();custom={id:cid,title:opts.custom.title,difficulty:opts.difficulty,category:'Custom',language:opts.language,problem:opts.custom.problem,input:opts.custom.input||'',output:opts.custom.output||'',constraints:opts.custom.constraints||'',exampleInput:tests[0].input,exampleOutput:tests[0].output,referenceSolution:opts.custom.solution,tests,hidden:tests};challengeStore.set(cid,custom);const vr=await runTests(custom,opts.language,opts.custom.solution,true);if(!vr.every(x=>x.pass))return socket.emit('error:game',{message:'Custom solution failed validation. Fix the solution/tests before creating the room.'});}catch(e){return socket.emit('error:game',{message:e.message||'Invalid custom challenge.'})}}const code='CB'+crypto.randomBytes(2).toString('hex').toUpperCase();rooms.set(code,{code,host:socket.user.id,language:opts.language,difficulty:opts.difficulty,custom,players:[{id:socket.user.id,username:socket.user.username,socketId:socket.id}]});socket.join('room:'+code);socket.emit('room:created',rooms.get(code))});
 socket.on('room:join',({code})=>{const r=rooms.get(code);if(!r)return socket.emit('error:game',{message:'Room not found or expired.'});if(r.players.length>=2)return socket.emit('error:game',{message:'Room is full.'});r.players.push({id:socket.user.id,username:socket.user.username,socketId:socket.id});socket.join('room:'+code);io.to('room:'+code).emit('room:state',r);socket.emit('room:joined',r)});
 socket.on('room:start',({code})=>{const r=rooms.get(code);if(!r||r.host!==socket.user.id||r.players.length!==2)return;const opts={language:r.language,difficulty:r.difficulty,custom:r.custom};const g=createGame(r.players,opts,false);r.gameId=g.id});
 socket.on('round:sabotage:update',({code,source})=>{const g=games.get(code);if(!g||g.phase!=='sabotage'||g.roles[socket.user.id]!=='saboteur')return;const n=diffChangedLines(g.originalCode,source);if(n<=g.maxChanges){g.currentCode=source;socket.emit('game:sabotageCount',{count:n,max:g.maxChanges})}});
 socket.on('round:lock',({code,source})=>{const g=games.get(code);if(!g||g.phase!=='sabotage')return;if(g.roles[socket.user.id]!=='saboteur')return socket.emit('error:game',{message:'Only the Saboteur can lock sabotage.'});const n=diffChangedLines(g.originalCode,source);if(n<1)return socket.emit('error:game',{message:'Make at least one change before locking.'});if(n>g.maxChanges)return socket.emit('error:game',{message:`Maximum ${g.maxChanges} changed lines allowed. Server counted ${n}.`});lockSabotage(g,source);});
 socket.on('round:debug:update',({code,source})=>{const g=games.get(code);if(!g||g.phase!=='debug'||g.roles[socket.user.id]!=='debugger')return;g.currentCode=source;const sab=g.players.find(p=>p.id!==socket.user.id);if(sab)io.to(sab.socketId).emit('game:liveCode',{source})});
 socket.on('round:submit',async({code,source})=>{const g=games.get(code);if(!g||g.phase!=='debug')return;if(g.roles[socket.user.id]!=='debugger')return;const c=g.challenge;const results=await runTests(c,g.language,source,true);io.to(g.id).emit('game:testResult',{tests:results});if(results.every(x=>x.pass)){g.scores[socket.user.id]=(g.scores[socket.user.id]||0)+1;g.resultMessage='Debugger fixed the program!';g.winnerId=null;g.phase='ended';g.phaseLabel='ROUND COMPLETE';db.prepare('UPDATE Rounds SET result=? WHERE match_id=? AND round_number=?').run('debugger',g.id,g.roundNumber);broadcast(g);setTimeout(()=>nextRound(g),1800)}});
 socket.on('fairplay:exit',({code})=>{const g=games.get(code);if(!g||!g.ranked||g.phase==='ended')return;g.fsViolations=g.fsViolations||{};g.fsViolations[socket.user.id]=(g.fsViolations[socket.user.id]||0)+1;const n=g.fsViolations[socket.user.id];io.to(socket.id).emit('fairplay:count',{count:n});if(n>=3){const winner=g.players.find(p=>p.id!==socket.user.id)?.id;if(winner){g.winnerId=winner;g.scores[winner]=Math.max(g.scores[winner]||0,3);g.resultMessage='Match forfeited: fullscreen exited three times.';finishMatch(g)}}});
 socket.on('fairplay:timeout',({code})=>{const g=games.get(code);if(!g||!g.ranked||g.phase==='ended')return;const winner=g.players.find(p=>p.id!==socket.user.id)?.id;if(winner){g.winnerId=winner;g.scores[winner]=Math.max(g.scores[winner]||0,3);g.resultMessage='Match forfeited: fullscreen was exited for more than 10 seconds.';finishMatch(g)}});
 socket.on('disconnect',()=>{for(const q of queues.values()){const i=q.findIndex(x=>x.socketId===socket.id);if(i>=0)q.splice(i,1)}for(const g of games.values()){const p=g.players.find(x=>x.socketId===socket.id);if(p&&g.phase!=='ended'){io.to(g.id).emit('opponent:disconnected',{message:`${p.username} disconnected. Match ended.`});g.phase='ended';g.phaseLabel='MATCH ENDED';broadcast(g)}}});
});
const clientDist=path.join(__dirname,'../client/dist');if(fs.existsSync(clientDist)){app.use(express.static(clientDist));app.get('*',(req,res)=>res.sendFile(path.join(clientDist,'index.html')))}
const PORT=process.env.PORT||4000;server.listen(PORT,()=>console.log(`CodeBattle server listening on http://localhost:${PORT}`));
